# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MC3-Running' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Core', :inhibit_warnings => true
  pod 'Firebase/Database', :inhibit_warnings => true
  pod 'Firebase/Auth', :inhibit_warnings => true
  pod 'Firebase/Storage', :inhibit_warnings => true
  pod 'Charts'
  # Pods for MC3-Running

end
